### PR TITLE
Improve the feature about options

### PR DESCRIPTION
**Pull request by finscn**
Improve the feature about options

Now command line options could be any one in NWBuilder.

And  some code  cosmetics (I format code with  https://github.com/beautify-web/js-beautify )

### CODE REVIEW

**Comment by finscn** [comment]
@adam-lynch  ,  Did you review it ?

**Comment by finscn** [comment]
You've ignored this PR, I'm so sad.
I know if just want to fix the issue about flavor in https://github.com/nwjs/nw-builder/commit/8d665223fea6eac6b8e4f7ff0afb6eb7149f2709  is very easy.

But it's palliatives.

The key point of the reason of that issue is "not manage options correctly".

I'm a Chinese guy, and my english is very poor , I can't explain my opinions clearly.
But I know the @rogerwang  could understand Chinese ,so  please forgive me , I have to say something in Chinese.

现在的 nw-builder 有一个很大的问题， 就是对 opitons 的使用和管理方式。
现在的版本里， 分别定义了两份  options， 一个在 index.js里， 一个在 nwbuild.js 里。 一旦有一个要修改，另外一个也要修改，如果忘记了或者没有做好同步，那么就容易产生bug。
之前 flavor 的那个bug 就与此有一定关系。

另外还有一个问题，就是对 options 中选项的默认值的设置问题。对于那些不是布尔型的变量， 也使用了 false，而不是 null做默认值，我觉得这种做法是有潜在风险的。

我的这个版本虽然不能说有多好， 但是解决了上述的两个问题， 我觉得是一个应该被考虑的方案。
希望你们能真的去review一下我的这个修改版本。

即使最终没有采用也无所谓，至少希望你们能重视一下现在的代码里的 Bad Smell 。

谢谢。

Thank you and Sorry for my poor English.

**Comment by adam-lynch** [comment]
I'm sorry about this. I've had a lot on my plate. Thanks for your code and comments nonetheless!

**Comment by rogerwang** [comment]
@finscn I'm not much a JavaScript programmer. So this project has been under community efforts and has been maintained by @adam-lynch , who proposed transferring this repo from his personal account to the nwjs organization. Recently Adam has less time for the project and has been looking for new maintainers in https://github.com/nwjs/nw-builder/issues/327 .

Is there any progress on the new maintainers @adam-lynch ?

**Comment by adam-lynch** [comment]
@rogerwang we've added one. That's all. More are definitely welcome.

**Comment by rogerwang** [comment]
Who is the new maintainer?

**Comment by adam-lynch** [comment]
@rogerwang, meet @DblK 😄

Note: I've also added this [team](https://github.com/nwjs/nw-builder#team) section to the readme, hoping it would help.

**Pull request closed without merging**
