### PR TITLE
resolved conflicts of pr #340 and fixed tests

### PR DESCRIPTION
**Pull request by langco**

### CODE REVIEW

**Comment by DblK** [comment]
Thank you very much for your work. I didn't get the time to do this work.

**Comment by adam-lynch** [comment]
Great, thanks @langco. It seems like there are some conflicts with the target branch to resolve. Also, the version should be 3.1.0 now.

**Comment by adam-lynch** [comment]
Just manually tested it and it seems to work well 👍

**Comment by langco** [comment]
You are welcome. I will have a look at the conflicts and update the pull request.

**Comment by langco** [comment]
Resolved all conflicts.

**Comment by adam-lynch** [comment]
Thanks a million again.

**Pull request merged**
