### PR TITLE
Nwjs 13 support

### PR DESCRIPTION
**Pull request by jontro**
Hello, here is the code for what I have been using for successfully building nwjs 13-rc2.

I have only been able to test mac and windows versions.

### CODE REVIEW

**Comment by flippyhead** [comment]
Thanks for this. I'm getting the following error when changing the version to `0.13.0-rc2`:

```
Using v0.13.0-rc2
Create cache folder in /Users/peter/Development/fetching-nw/cache/0.13.0-rc2
Downloading: http://dl.nwjs.io/v0.13.0-rc2/nwjs-v0.13.0-rc2-osx-ia32.zip
Create cache folder in /Users/peter/Development/fetching-nw/cache/0.13.0-rc2
Downloading: http://dl.nwjs.io/v0.13.0-rc2/nwjs-v0.13.0-rc2-osx-x64.zip
  downloading [--------------------] 0% 65.0sERROR: The version 0.13.0-rc2 does not have a corresponding build posted at http://dl.nwjs.io/. Please choose a version from that list.
```

I see that version in the list so not sure how to proceed.

**Comment by drom** [comment]
@jontro for the `linux{32|64}` case you need to copy `lib/` folder.

```
cache/0.13.0-rc2/linux64/lib/
├── libffmpeg.so
├── libnode.so
└── libnw.so
```

**Comment by jontro** [comment]
@flippyhead Looks like they have dropped support for osx-ia32. Not sure how to proceed here, or if they intend to support it when they release the 0.13 final release
@drom Added ffmpeg.dll and the lib files, thanks.

**Comment by evshiron** [comment]
Nice work, hope it will be merged soon.

**Comment by RPereiraRedspark** [comment]
really nice @jontro, what i did to solve this issue for now was to make a copy of platforms.js and create a gulp task that overwrites the nw-builder/lib/platforms.js before i require it, this way i kept fixing it as the requirements changed, once this fix is merged i can drop this solution

**Comment by jontro** [comment]
Yep, great suggestinon @RPereiraRedspark. Don't forget to copy lib/index.js as well if you rely on icons on mac. Now that 0.13.0 has been released it might make sense to look more into this. 

http://nwjs.io/downloads/ does not list mac os 32 any more. I don't think there are many people running 32 bit versions of mac so maybe that's why they have dropped it.

However as platform.js is lain out I do not see an easy way of disabling the 32 bit version for osx if version is >= 0.13.0

Does anyone have suggestions?

**Comment by evshiron** [comment]
@RPereiraRedspark I am doing it by `npm install https://github.com/jontro/nw-builder#nwjs-13`, and [check the docs](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) if it helps a bit :)

**Comment by vsa** [comment]
What's blocking this? The problem with 32-bit OS X versions seems to be a separate issue to me.

**Comment by bastimeyer** [comment]
I'd say there is no point in merging this yet until #275 has been resolved. The new NW.js releases will be coming much faster now, so the builder is much likely to break again without this.

There are also different build flavors now with `0.13.0`. Since this PR does only support the default flavor, you won't be able to access the dev tools. There needs to be another change for the `build` and the `run` method, which should use different build flavors.

**Comment by evshiron** [comment]
@bastimeyer Sounds reasonable.
And as a temporary solution for now, I maintain a fork of `nw-builder` at `evshiron/nw-builder` and have this PR merged along with some other commits which add support for SDK/NaCl versions.
As far as I know, building for `win32` and running on `osx64` works for normal/SDK versions. The others remain untested.
```
$ npm install evshiron/nw-builder -g
$ nwbuild -v 0.13.0-rc3-sdk -r ./build/
Using v0.13.0-rc3-sdk
Create cache folder in /usr/local/lib/node_modules/nw-builder/cache/0.13.0-rc3-sdk
Downloading: http://dl.nwjs.io/v0.13.0-rc3/nwjs-sdk-v0.13.0-rc3-osx-x64.zip
  downloading [====================] 100% 0.0s

Launching App
App exited with code 0
```

**Comment by parthi82** [comment]
@evshiron Hi, I'm trying to upgrade my app which using nwjs 0.12.2 to latest version of nwjs. when i build my app using your nw-builder fork and run it on windows it says "unable to find locale data files. Please reinstall". i tried building for both v0.13.x and v0.14.x but i have the same problem.

**Comment by evshiron** [comment]
@parthi82 Greeting! I have never seen that message before, and I fail to reappear on my Windows 7. Could you please:
1. Try launching it on another Windows computer and see if it works.
2. Try downloading raw nw.js executables from http://nwjs.io/ and see if it works with your application without packaging.
The above steps should provide more information.

**Comment by larssb** [comment]
Do anyone know when we might see this fix incorporated into nw-builder? I still get the error "ffmpegsumo.dll missing" (#309) when I build my NW app with nw-builder on Windows 2008R2 with the newest version of nw-builder and targeting the latest release of nwJS. It work when I go all the way back to v12.0.3. Would be great to avoid fiddling around with the platforms.js file and such. 

Looking forward to hearing from you and thank you very much.

**Comment by evshiron** [comment]
@larssb No idea, it has been inactive for quite a while. And a temporary solution should have been described above.

**Comment by mato75** [comment]
I cannot get it to work with npm install jontro/nw-builder#nwjs-13. Still getting this issue:

ERROR: The version 0.14.3 does not have a corresponding build posted at http://dl.nwjs.io/. Please choose a version from that list.
Unable to download nodewebkit. undefined

**Comment by atlantidezign** [comment]
i posted my solution in  #320

**Comment by adam-lynch** [comment]
Thanks a lot but we're going to redo how we do a lot of this. This no longer suits. See the plan at #327. Any help is more than welcome.

**Comment by linquize** [comment]
See #333

**Pull request closed without merging**
