### PR TITLE
Download NW.js archives via https

### PR DESCRIPTION
**Pull request by bastimeyer**
Secure downloads should be the default...
https://github.com/nwjs/nw.js/issues/3228#issuecomment-237153818

### CODE REVIEW

**Comment by adam-lynch** [comment]
This should just update to `https`. Addition of the `manifestUrl` option should be another PR. Is it really needed anyway?

**Comment by bastimeyer** [comment]
My idea behind this was enabling a future addition of custom manifestUrls in the builder options, since the downloadUrl can be customized already. Theoretically it is not needed and the https manifest url should be used at all times, but without this change all tests would need to be updated, too, and this was the simpler approach.
I'm fine with closing this PR if you want to change it and upgrade everything by yourself.

**Comment by DblK** [comment]
Since we change the file, could you update your pull request to resolve the conflicts?
After the review, I will merge it.

**Comment by bastimeyer** [comment]
Conflicts solved, rebased and PR updated...
I've also added the `manifestUrl` option. Should I add this to the readme? The `downloadUrl` option is not listed in the readme, so I was not sure.

Btw, the flavors addition which caused these conflicts doesn't seem to have any tests. Also, the `flavor` parameter in `getLegacyVersions`, `getVersionsFromManifest`, `getLatestVersion`, `getVersion` and `getVersions` is never used. Just wanted to mention this...

**Comment by adam-lynch** [comment]
This is slightly related to #364 so `manifestUrl` would be handy, except there is no alternative location where `versions.json` is hosted.

I would've thought we could phase out `downloadUrl` until I saw #364.

Is there a benefit to having two separate properties (`manifestUrl` and `downloadUrl`)? I guess so?

**Comment by bastimeyer** [comment]
> Is there a benefit to having two separate properties

Having one customizable url and another static one doesn't make sense IMO. How would you solve this problem instead? Both options don't share the same domain name.

The `manifestUrl` could be useful for people who have forked nwjs and are using their own builds with nwbuilder. It's also useful for people who are unable to access nwjs.io or who don't want to use https for whatever reason.

**Comment by bastimeyer** [comment]
@adam-lynch @DblK 
Is there something that needs to be changed?

**Comment by adam-lynch** [comment]
Thanks :smile:

**Pull request merged**
